### ISSUE TITLE
Digital Academy - Learn digital capabilities - MVP

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#144]
## User Story

As a public servant, I can find the learning programs and content that can help me build my digital capabilities.

###Conext 

The Digital Academy is a program under development. The scope and scale of what this academy includes is likely to change. In the interim, there is an opportunity to communicate what is currently available.

There are several digital related training courses and learning experiences offered across the BCPS (most not delivered through the PSA learning center) including (but not limited to):

- Agile fundamentals, Digital Leadership, Openshift 101/201, UX -[found at BCdevExchange.org] (https://bcdevexchange.org/learning)
- Data literacy (under development)
- Python, R
- Lean
- Behavioural Insights
- Apolitical Digital Bootcamp

Some of these are offered regularly, and others are not yet fully supported to meet demand. People want clarity on how to learn these skills. There is also a connection between these skills and communities of practice (or guilds). So we should be able to connect people who want to learn to others who are practicing.

# Acceptance Criteria (TBC)
- [ ] There is a list of courses and content that should be included in the Digital Academy space (work with Digital Academy Lead)
- [ ] The information about those courses is useful (user research)
- [ ] The content can be continuously improved by the Digital Academy team (uses the CMS)

**Comment by mark-a-wilson** [comment]
Stale epic. Have added "Content about Digital Learning Opportunities" feature to the wish list on the MIRO Roadmap board with link to this Issue.
