### ISSUE TITLE
How to Fund a Product

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#228]
## User Stories

As a product owner, I can understand how and when to ask for funding for my program areas digital service delivery needs.

## Context

Digital services are ideally delivered by teams that are continuously dedicated to improving them. When a digital product is started there is often a need for a capital investment, [given GAAP accounting rules](https://smallbusiness.chron.com/gaap-rules-capital-expenditures-77592.html#:~:text=Under%20GAAP%2C%20companies%20can%20capitalize,useful%20life%20of%20the%20asset.)

Additionally, we fund ongoing service delivery with operational budget, which includes staff time and maintenance. 

It is difficult to know how to apply funding rules, particularly given the ongoing investment in new features that might occur as we get feedback from people using our services. Teams are not necessarily considered assets, but if they are funded properly, they can create significant new assets that might traditionally be considered capital.

There are also a variety of processes for allocating funds, and for capital, there is a carefully managed process to ensure that public dollars are being spent effectively and efficiently.

Some of these processes are improving, given new standards for digital delivery. People visiting Digital.gov.bc.ca should be able to have clarity on how they might engage in these processes.

## Acceptance Criteria

- [ ] Illustrate funding journeys through real case studies.
- [ ] Provide clear instructions and requirements.
- [ ] Additional criteria TBC post user research.

**Comment by mark-a-wilson** [comment]
In my view, this is an example of an Epic which we could/should be farming out. 

Who "owns" these funding processes? Who should be explaining/providing advice on how to get funding for digital delivery?

**Comment by mark-a-wilson** [comment]
Closing this stale epic. Will recreate when necessary.
