### ISSUE TITLE
Turn WCAG 2 Checklist into a spreadsheet for documenting audits

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#234]
Now that we have a standard to meet for accessibility (everything A and AA in the [WCAG 2 Checklist](https://webaim.org/standards/wcag/checklist
)), we need to track our audit of pages and record remedial work that needs to be done.

#### Acceptance Criteria
Spreadsheet contains all standards in the WCAG 2 Checklist and is set up to capture:
- [x] Name of auditor
- [x] Page that was audited (URL of deployment)
- [x] Whether the standard is met (binary choices: YES, NO, or N/A)
- [x] Notes column to describe how the standard isn't being met
- [x] Column for link to GitHub issue where the remedial work needed is described

**Comment by mark-a-wilson** [comment]
Here is the accessibility audit spreadsheet: https://docs.google.com/spreadsheets/d/122aEH7rIJAcbV5o3c3grYkkI_eLE0mQ0RT2_lumzM5I/edit#gid=0
