### ISSUE TITLE
Digital Framework Content Administration

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#341]
### User Story
As the owner of content about the **Digital Framework**, I would like to publish, and edit/maintain content to reflect updates to, and progress being made on, the Digital Framework on digital.gov.bc.ca.

### Acceptance Criteria
- [ ] A frontend UI has been built that meets Kim's desires for the content they want to publish 
- [ ] Kim can **log in** to the Strapi CMS and find the piece of content she owns
- [ ] Kim can **create/edit** her piece(s) of content
- [ ] Kim can **preview** how her content will look in production before publishing it
- [ ] Kim can **publish** her content to production

Pieces of work that would need to be done by the **digital.gov.bc.ca team** to make this happen (see [this blueprint](https://miro.com/app/board/o9J_kkUfXEo=/) for a rough process):
- [ ] Co-design with Kim a frontend UI that will meet her needs (mostly done, see #287, #288)
- [ ] Build the frontend UI
- [ ] (If no suitable Strapi CMS content model exists) Create a content model for the content
- [ ] (If a suitable Strapi CMS content model already exists) Assign a content model for the content
- [ ] Create the content object(s) in Strapi CMS and assign privileges to Kim
- [ ] Configure Strapi CMS login
- [ ] Connect frontend UI and content model
- [ ] Build and deploy a TEST/PREVIEW environment for previewing content before it's published
- [ ] Configure frontend and Strapi backend with production environment

** Tickets to be created in Technical breakout session **

**Comment by mark-a-wilson** [comment]
Closing this stale epic. Will redefine Digital Framework work when the time comes.
