### ISSUE TITLE
Digital Academy 

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#344]
(1) Develop a work plan with Derek Masselink on the implementation of a Digital Academy. 
(2) Design the pages
(3) Develop content
(4) Implement technical solution using Strapi

**Comment by mark-a-wilson** [comment]
@nmathava - here's what I'd suggest:

### User Story
As the **Director for the Digital Academy**, I would like to publish, and edit/maintain content about the Digital Academy on digital.gov.bc.ca.

### Acceptance Criteria
- [ ] A frontend UI that meets Derek's desires for the content he wants to publish has been built 
- [ ] Derek can **log in** to the Strapi CMS and find the piece of content he owns
- [ ] Derek can **create/edit** his piece of content
- [ ] Derek can **preview** how his content will look in production before publishing it
- [ ] Derek can **publish** his content to production

Pieces of work that would need to be done by the **digital.gov.bc.ca team** to make this happen (see [this blueprint](https://miro.com/app/board/o9J_kkUfXEo=/) for a rough process):
- [ ] Co-design with Derek a frontend UI that will meet his needs
- [ ] Build the frontend UI
- [ ] (If no suitable Strapi CMS content model exists) Create a content model for the content
- [ ] (If a suitable Strapi CMS content model already exists) Assign a content model for the content
- [ ] Create the content object(s) in Strapi CMS and assign privileges to Derek
- [ ] Configure Strapi CMS login
- [ ] Connect frontend UI and content model
- [ ] Build and deploy a TEST/PREVIEW environment for previewing content before it's published
- [ ] Configure frontend and Strapi backend with production environment

**Comment by mark-a-wilson** [comment]
Stale Epic. Will create new Epics if/when necessary.
