### ISSUE TITLE
Content: Common Components

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#345]
#### Value / Outcome / Why are we doing this?

We believe that featuring common components on digital.gov.bc.ca may help increase their uptake.

#### User Stories

As a **visitor** to digital.gov.bc.ca, I can read about common components that have been built.

As a **content manager**, I can add info about new common components to the collection without needing a developer.

#### Acceptance Criteria

- [x] UI design of common components meets Common Components Team's requirements for MVP
- [x] Common Components Team can manage content via Strapi
- [ ] CoCo index page can be navigated to from other pages on the site

**Comment by HeatherRemacle** [comment]
Update: Given broad interest s from multiple teams wanting to publish content to Digital.gov, we have decided to build the dynamic, database driven CMS, Strapi, and will publish our CoCo MVP using that approach.

Note the ownership of future CoCo content is TBD.

**Comment by bdolor** [comment]
closing
