### ISSUE TITLE
[CONTENT] The Advantages of Digital Service Delivery

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#35]
[Content Template >](https://docs.google.com/document/d/1l5AwoAkM0sceboy80RozAYQ9cNE2LF8b-RzSiiUaqb4/edit)

Target audience (_Who is this content for?_): Government executives (organization leaders) and service owners / would-be product owners.

Desired outcome (_What do we want this content to help the reader understand or do?_):  Following our clear definition of what digital service delivery approach is, to understand and be convinced why this approach should be taken, what are its advantages.

#### Acceptance Criteria

- Add any specific acceptance criteria here, or delete this heading.

#### Definition of Done

- [ ] Content template completed in Google Drive; link included 
- [ ] Content has been reviewed by someone other than the writer(s) (another team member, or a government employee outside our team) 
- [ ] Content has been approved for publication by Product Owner

#### Process

* **Assignee** - In the Google Drive [Content folder](https://drive.google.com/drive/u/2/folders/1YezB6ZLpTqun9Gb8tSf3bU81vhB5MZtL), make a new document from the document called ****Content Writing Template**** (right click > Make a Copy). After 1 and 2 of DOD are complete, move Issue to the 'For PO to Review' column
* **Product Owner** - If content is approved with no revisions necessary, move Issue to the 'Closed' column. If revision required, make comments in the Google Doc and move Issue back into the 'In Progress' column, and @tag the assignee.
