### ISSUE TITLE
OCP4 Migration

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#464]
#### Value / Desired Outcome / Why are we doing this? 
In order to deploy our product after March 2021, we must move it out of OCP3 and into OCP4. When this epic is complete, we will be "up and running" in OCP4 and able to deploy our site in production (#187).

#### User Story

As the product owner for digital.gov.bc.ca, I can be confident that digital.gov.bc.ca is functioning in the OCP4 platform.

#### Acceptance Criteria
- [x] Code is in OCP4 
- [x] Developers are able to control development and deployment 
- [x] Platform Services has been notified that they may now remove our OCP3 namespaces (Mark or Parul need to submit [this request form](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+mitovskaol%2C+ShellyXueHan&labels=openshift-project-set%2C+pending&template=openshift_project_request.md&title=))

**Comment by mark-a-wilson** [comment]
Epic complete! 💥🎉 Thanks, @parulmishra !
