### ISSUE TITLE
Feature: A way for site visitors to submit feedback

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#518]
#### Value / Desired Outcome / Why would we do this?
The more intelligence we have (even if it is anecdotal) about what people are trying to do and what information they are looking for, the more evidence we'll have to decide what content we need to make easier to find, or create, or what aspects of the site are causing problems.

#### User Story
As a visitor to digital.gov.bc.ca, I can easily submit my feedback on the site.

As the product owner for digital.gov.bc.ca, I would like to know what reasons public servants are visiting the site — what tasks they are struggling to complete, what information they are looking for. I'd like the website to have an engaging and desirable way for visitors who are so inclined to quickly provide that feedback.

#### Acceptance Criteria
- [x] The feature communicates to the user that we're particularly interested in what they were looking for during their visit
- [x] The feature captures the date on which the user submitted the feedback
- [x] Team members (particularly the product owner and UX designer) have a way to easily review feedback that has been submitted without needing to request a data dump from a developer (i.e. the feedback data is easily accessible at all times)
