### ISSUE TITLE
Content: Digital Framework Progress Report

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#542]
#### Value / Why are we doing this?
The Digital Delivery Unit (CDO's office) wants to publish content that reports on progress made towards the Digital Framework. This content is currently live on the WordPress site: https://digital.gov.bc.ca/digital-framework-progress/.

#### User story
As a visitor, I can see a video and read content that shows progress that's been made to date on the Digital Framework.

#### Acceptance Criteria
- [x] UI realizes the design in [this prototype](https://www.figma.com/proto/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=0%3A1)
- [x] Content can be modified in future via Strapi
- [x] All of the content (including video embed) published on the WP site (see: https://digital.gov.bc.ca/digital-framework-progress/) is incorporated

**Comment by mark-a-wilson** [comment]
@singhinderdeep — for the design, I came up with this mockup a couple of months ago and ran it by Kim and Danny: https://www.figma.com/proto/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=2531%3A30&scaling=min-zoom.  I am totally open to a different design of your devising.

To view the way this content will appear in the WP site for now, see this link (you'll need to be logged in to VPN to view):
https://test.workingforyou.gov.bc.ca/digital/digital-framework-progress
