### ISSUE TITLE
Content: Hosting and Application Development Strategy

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#643]
The Hosting and Application Development Strategy (HADS) has been finalized and approved for publishing.

#### Acceptance Criteria
- [ ] The HADS is visually featured somehow (i.e. make if more than a link) on the **Resources** page, under the **Standards & Policy** heading.

- [ ] The teaser for the feature reads:
> **Hosting and Application Development Strategy**
> Vision and approach for modernizing government’s efforts to provide excellent digital services by using best practices.

- [ ] The teaser links to [this document](https://drive.google.com/file/d/17osSyW1lEv1w8K3PC6NgmzaCuugiyx0P/view?usp=sharing) in PDF format. Clicking on the link should make the PDF load within the browser page rather than triggering a document download.
