### ISSUE TITLE
Feature: Digital Trust

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#717]
#### Value / why are we doing this?
The Digital Trust team has been leading some cutting edge. We'd like the Province to get more credit for leading this work, and add credibility to the content around the work, by aligning it with the central "digital.gov.bc.ca" domain.

#### Acceptance Criteria
- [ ] The digital trust WordPress site has been styled to align with Gov/Design System branding
- [ ] The digital trust WordPress site is live at **digital.gov.bc.ca/digital-trust**
- [ ] It has been decided and documented who will maintain and approve Digital Trust content  
- [ ] digital.gov.bc.ca features and links out to the digital trust WordPress site in appropriate place(s) (e.g. Case Studies, Products & Services, main nav, and/or homepage, TBD)
