### ISSUE TITLE
Reverse Proxy for Digital Marketplace

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#746]
#### Description of Task 

- Create new reverse proxy for Digital Marketplace based on existing proxy
- Backup plan: if Caddy doesn't work. Try replacing with nginx.

#### Notes
- WIP Caddyfile located here => https://github.com/bcgov/digital.gov.bc.ca/pull/708/files 

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Add any specific acceptance criteria here, or delete this heading.

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build
